import { Injectable, Logger } from '@nestjs/common';
import { PrAnalyzerDto } from '../../../dto/queue-payload/pr-analyzer-payload.dto';
import { LlmService } from '../../../../ai/service/llm-call.service';
import { PrCodeParsingService } from '../pr-code-parsing/pr-code-parsing.service';
import { PullRequestQueryService } from '../../query/pull-request-query/pull-request-query.service';
import { RepoLlmConfigService } from '../../../../llm/service/repo-llm-config.service';
import { CredentialService } from '../../../../llm/service/credential.service';
import { PullRequestReviewService } from '../../../service/pull-request-review/pull-request-review.service';
import { ReviewCancellationService } from './review-cancellation.service';
import { LlmCancelledError } from '../../../../ai/errors/llm-provider.error';
import { LlmExecutionContext } from '../../../../ai/dto/execution-context.dto';
import { LlmRequest } from '../../../../ai/dto/llm-request.dto';
import { ProviderCredentials } from '../../../../ai/dto/provider-credentials.dto';
import {
  FileContextDto,
  PullRequestMetadataDto,
  PullRequestReviewContextDto,
} from '../../../dto/review/pr-review-context.dto';
import { CODE_REVIEW_SYSTEM_PROMPT } from '../../../util/prompt-utils';
import { RepoLlmConfigResponseDto } from '../../../../llm/dtos/repo-llm-config-response.dto';
import {
  LlmResponse,
  LlmResponseDto,
} from '../../../../ai/dto/llm-response.dto';
import { z } from 'zod';
import { AIReviewResponseSchema } from '../../../../ai/schema/ai-review-comment.schema';
import { Queue } from 'bullmq';
import { InjectQueue } from '@nestjs/bullmq';
import { ReviewResultsPayloadDto } from '../../../dto/review/review-results-payload.dto';

@Injectable()
export class AiReviewService {
  private readonly logger = new Logger(AiReviewService.name);
  private readonly MAX_FILES_PER_BATCH = 3;

  constructor(
    private readonly llmCallService: LlmService,
    private readonly prCodeParsingService: PrCodeParsingService,
    private readonly pullRequestQueryService: PullRequestQueryService,
    private readonly repoLlmConfig: RepoLlmConfigService,
    private readonly credentialService: CredentialService,
    private readonly pullRequestReviewService: PullRequestReviewService,
    private readonly reviewCancellationService: ReviewCancellationService,
    @InjectQueue('pull-request-review-results')
    private readonly pullRequestReviewQueue: Queue,
  ) {}

  async handleAiReview(prPayload: PrAnalyzerDto): Promise<LlmResponseDto> {
    // TODO: handle idemptoency and cancellation of old reviews in case pr is updated simulataneously.
    // TODO: Handle prevention of duplicate comments on the codes for subsequent runs of review for pr, either by keeping track of comments posted for a pr, or by making the comment posting logic idempotent by design, so that even if duplicate comments are generated by llm for some reason, only one set of comments get posted on the pr.

    // TODO: Check how review works for moved files or renamed files
    const githubRepositoryId = prPayload.repositoryId.toString();
    const pullRequestId = prPayload.pullRequestId;

    const runId = `pr-review:${pullRequestId}:${Date.now()}`;

    this.logger.log(
      `Handling ai review for PR: ${pullRequestId}, repositoryId: ${githubRepositoryId}`,
    );

    if (!githubRepositoryId || !pullRequestId) {
      this.logger.warn(
        `Missing repositoryId or pullRequestId for job metadata.`,
      );
      return {};
    }

    const pullRequest =
      await this.pullRequestQueryService.findPullRequestByIdWithRepositoryAndInstallation(
        pullRequestId,
      );

    if (!pullRequest) {
      this.logger.warn(
        `PR entity records not found in database: ${pullRequestId}`,
      );
      return {};
    }

    const pullRequestNumber = pullRequest.prNumber ?? 0;
    const headBranchSha = pullRequest.headSha ?? '';
    const installationId = pullRequest.repository.installation.installationId;
    const repositoryFullName = pullRequest.repository.fullName;

    if (pullRequest.isMerged) {
      this.logger.warn(
        `PR ${pullRequestId} already merged. Skipping review sequence.`,
      );
      return {};
    }

    const llmConfig =
      await this.repoLlmConfig.getRepoLlmConfigByRepositoryId(
        githubRepositoryId,
      );
    if (
      !llmConfig ||
      llmConfig.isActive === false ||
      !llmConfig.isValid ||
      !llmConfig.model
    ) {
      this.logger.warn(
        `LLM config for repository ${githubRepositoryId} is inactive or invalid. Skipping review.`,
      );
      return {};
    }

    const decryptedLlmCredentials =
      await this.credentialService.getDecryptedConfigByProviderId(
        llmConfig.providerId,
      );

    const fileContext: PullRequestReviewContextDto =
      await this.prCodeParsingService.generateContextFromPullRequest(
        pullRequestId,
      );

    if (!fileContext.files || fileContext.files.length === 0) {
      this.logger.log(
        `No applicable code modifications found for review in PR ${pullRequestId}`,
      );
      return {};
    }

    const { supersededRunIds } =
      await this.pullRequestReviewService.createInProgressReviewJob(
        pullRequestId,
        llmConfig.providerType,
        runId,
      );

    for (const supersededRunId of supersededRunIds) {
      this.logger.log(
        `Superseding earlier review run ${supersededRunId} for PR ${pullRequestId}`,
      );
      await this.reviewCancellationService.publishCancellation(supersededRunId);
    }

    const abortSignal = this.reviewCancellationService.register(runId);

    const providerCredentials: ProviderCredentials = {
      apiKey: decryptedLlmCredentials.apiKey,
      baseUrl: decryptedLlmCredentials.baseUrl,
      provider: llmConfig.providerType,
    };

    const fileBatches = this.chunkFiles(
      fileContext.files,
      this.MAX_FILES_PER_BATCH,
    );

    this.logger.log(
      `PR ${pullRequestId} split into ${fileBatches.length} review execution batches.`,
    );

    const reviewPromises = fileBatches.map((batchFiles, index) => {
      this.logger.log(
        `Initiating review for batch #${index + 1} with ${batchFiles.length} files for PR ${pullRequestId}.`,
      );

      const llmProviderConfig: LlmExecutionContext = {
        credentials: providerCredentials,
        requestId: `repoId:${githubRepositoryId} | prId:${pullRequestId} | batch:${index + 1} | ${Date.now()}`,
        abortSignal,
      };

      return this.reviewFileBatch(
        batchFiles,
        fileContext.prMetadata,
        llmConfig,
        llmProviderConfig,
        index + 1,
        pullRequestNumber,
        headBranchSha,
        installationId,
        repositoryFullName,
      );
    });

    let batchResults:
      | Array<LlmResponse<z.infer<typeof AIReviewResponseSchema>> | null>
      | undefined;

    try {
      batchResults = await Promise.all(reviewPromises);
    } finally {
      this.reviewCancellationService.deregister(runId);
    }

    const successfulBatchResults = (batchResults ?? []).filter(
      (result): result is LlmResponse<z.infer<typeof AIReviewResponseSchema>> =>
        Boolean(result?.response),
    );

    if (successfulBatchResults.length === 0) {
      this.logger.warn(
        `No successful review batches for PR ${pullRequestId}. Skipping review result queue enqueue.`,
      );
      return {};
    }

    const consolidatedSummary = successfulBatchResults
      .map((result) => result.response.summary)
      .filter(Boolean)
      .join('\n\n');
    const comments = successfulBatchResults.flatMap(
      (result) => result.response.comments,
    );

    const result: LlmResponseDto = {
      totalTokenUsage: successfulBatchResults.reduce(
        (total, result) => total + (result.usage?.totalTokens ?? 0),
        0,
      ),
      totalInputTokens: successfulBatchResults.reduce(
        (total, result) => total + (result.usage?.promptTokens ?? 0),
        0,
      ),
      totalOutputTokens: successfulBatchResults.reduce(
        (total, result) => total + (result.usage?.completionTokens ?? 0),
        0,
      ),
      model: successfulBatchResults[0].model,
      provider: successfulBatchResults[0].provider,
      consolidatedSummary,
      comments,
    };

    const queuePayload: ReviewResultsPayloadDto = {
      runId: runId,
      provider: llmConfig.providerType,
      pullRequestId,
      githubRepositoryId,
      result,
    };

    this.logger.log(
      `Queueing pull request review result for PR ${pullRequestId}, runId=${runId}`,
    );

    const queuedJob = await this.pullRequestReviewQueue.add(
      'pull-request-review-results',
      queuePayload,
      {
        jobId: `pull-request-review-results-${pullRequestId}-${Date.now()}`,
        attempts: 5,
        backoff: {
          type: 'exponential',
          delay: 3000,
        },
        removeOnComplete: 1000,
        removeOnFail: 5000,
      },
    );

    this.logger.log(
      `Queued pull request review result job ${queuedJob.id} for PR ${pullRequestId}`,
    );

    return result;
  }

  private chunkFiles(
    files: FileContextDto[],
    size: number,
  ): FileContextDto[][] {
    const chunks: FileContextDto[][] = [];
    for (let i = 0; i < files.length; i += size) {
      chunks.push(files.slice(i, i + size));
    }

    this.logger.log(
      `Splitting PR files into ${chunks.length} review execution batches.`,
    );
    return chunks;
  }

  private async reviewFileBatch(
    files: FileContextDto[],
    metadata: PullRequestMetadataDto,
    llmConfig: RepoLlmConfigResponseDto,
    providerConfig: LlmExecutionContext,
    batchId: number,
    pullRequestNumber: number,
    headBranchSha: string,
    installationId: string,
    repositoryFullName: string,
  ): Promise<LlmResponse<z.infer<typeof AIReviewResponseSchema>> | null> {
    this.logger.debug(`Executing batch evaluation pass #${batchId}`);

    const userPromptText = `
Analyze the structural code modifications for this designated batch segment.
Review the code changes with strict isolation principles.

PR General Scope:
- Title: ${metadata.title}
- Intent: ${metadata.body}

Target Batch Files to Evaluate:
${JSON.stringify(files, null, 2)}
`;

    const llmRequest: LlmRequest<typeof AIReviewResponseSchema> = {
      model: llmConfig.model,
      systemPrompt: CODE_REVIEW_SYSTEM_PROMPT,
      messages: [
        {
          role: 'user',
          content: [{ type: 'text', text: userPromptText }],
        },
      ],
      temperature: 0.1,
      maxTokens: 3000,
      topP: 0.9,
      stream: false,
      responseSchema: AIReviewResponseSchema,
      headBranchSha: headBranchSha,
      pullRequestNumber: pullRequestNumber,
      installationId: installationId,
      repositoryFullName: repositoryFullName,
    };

    try {
      const llmResponse: LlmResponse<z.infer<typeof AIReviewResponseSchema>> =
        await this.llmCallService.generate(
          llmConfig.providerType,
          llmRequest,
          providerConfig,
        );

      if (!llmResponse.response) {
        throw new Error(
          'Received an empty text payload from the underlying LLM provider adapter.',
        );
      }

      return llmResponse;
    } catch (error: unknown) {
      if (error instanceof LlmCancelledError) {
        this.logger.warn(
          `Review batch #${batchId} cancelled for PR ${pullRequestNumber}`,
        );
        return null;
      }

      const errorMessage =
        error instanceof Error ? error.message : String(error);
      this.logger.error(
        `Critical parsing error encountered on batch processing step #${batchId}: ${errorMessage}`,
      );

      return null;
    }
  }
}
