export enum ReviewWorkflowEventType {
  STEP_STARTED = 'STEP_STARTED',
  STEP_COMPLETED = 'STEP_COMPLETED',
  STEP_FAILED = 'STEP_FAILED',
  RUN_COMPLETED = 'RUN_COMPLETED',
  RUN_FAILED = 'RUN_FAILED',
  RUN_CANCELLED = 'RUN_CANCELLED',
  RUN_SUPERSEDED = 'RUN_SUPERSEDED',
  RUN_CREATED = 'RUN_CREATED',
}
