version: '3.9'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    restart: unless-stopped
    environment:
      COLLECTOR_OTLP_ENABLED: 'true'
    ports:
      # Jaeger UI
      - '16686:16686'
      # OTLP HTTP
      - '4318:4318'
      # OTLP gRPC
      - '4317:4317'
      # Jaeger Collector HTTP
      - '14268:14268'
      # Jaeger Collector gRPC
      - '14250:14250'
    healthcheck:
      test: [ 'CMD', 'wget', '--spider', '-q', 'http://localhost:16686' ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: ankane/pgvector:latest
    container_name: pgvector-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
